# -*- coding: utf-8 -*-
"""pythonrepo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Au3emeRemGdqtiAoSvN9YnxIidxE763
"""

print("Hola mundo");